import { env } from '../config.js';
import { logger, type RunErrors } from '../logger.js';
import { AiProvider, buildSystemPrompt } from './provider.js';
import { fallbackDaily } from '../analysis/fallback.js';
import { truncate } from '../security/sanitize.js';
import { DailyAnalysisSchema, type AnalyzedItem, type DailyAnalysis } from '../types.js';

/**
 * วิเคราะห์ภาพรวมประจำวัน (AI pass ที่ 2)
 * ใช้ adaptive thinking + effort สูง เพราะเป็นงานสังเคราะห์เชิงกลยุทธ์ครั้งเดียวต่อวัน
 */
export async function analyzeDaily(
  items: AnalyzedItem[],
  provider: AiProvider,
  errors: RunErrors,
): Promise<{ daily: DailyAnalysis; by: 'ai' | 'fallback' }> {
  if (!provider.enabled || !provider.withinBudget || items.length === 0) {
    return { daily: fallbackDaily(items), by: 'fallback' };
  }

  // ส่งเฉพาะข่าวที่มีนัยสำคัญที่สุด เพื่อคุมขนาด context
  const ranked = [...items]
    .sort((a, b) => Math.abs(b.impactScore) * b.confidence - Math.abs(a.impactScore) * a.confidence)
    .slice(0, 35);

  const payload = ranked.map((i) => ({
    id: i.id,
    titleTh: i.titleTh,
    summary: truncate(i.shortSummaryTh, 260),
    classification: i.classification,
    impactScore: i.impactScore,
    confidence: i.confidence,
    category: i.newsCategory,
    channels: i.affectedChannels,
    products: i.affectedProducts,
    countries: i.affectedCountries,
    competitors: i.affectedCompetitors,
    okr: i.okrImpact,
    source: i.sourceName,
    tier: i.sourceTier,
  }));

  const stats = {
    total: items.length,
    positive: items.filter((i) => i.classification === 'positive').length,
    neutral: items.filter((i) => i.classification === 'neutral').length,
    negative: items.filter((i) => i.classification === 'negative').length,
    competitorMentions: items.filter((i) => i.affectedCompetitors.length > 0).length,
  };

  try {
    const daily = await provider.generate({
      system: buildSystemPrompt('daily-executive-analysis.md'),
      userContent: `สถิติวันนี้: ${JSON.stringify(stats)}\n\nรายการข่าวที่วิเคราะห์แล้ว:\n${JSON.stringify(payload, null, 1)}`,
      schema: DailyAnalysisSchema,
      effort: env.aiEffortDaily as 'high',
      thinking: true,
      maxTokens: 8000,
      cacheSystem: true,
    });
    logger.info('daily executive analysis generated by AI');
    return { daily, by: 'ai' };
  } catch (err) {
    errors.capture('ai:daily', err);
    return { daily: fallbackDaily(items), by: 'fallback' };
  }
}
